@startuml

|#lightgreen|Doris| 

start

:Generate directories 
from subset of commits
in a Git repo;

|#lightgreen|jdt2famix|
:Directory tree of commits, 
e.g., ./0/, ./1/, etc.]
:Create MSE file for 
each commit, e.g., 
./0/0.mse, ./1/1.mse, etc.;

|MOOSE/Pharo|
:Analyse MSE files;

|Git bash|
:Calculate churn;

|Emprical study|
:Data from analysis]
:Perform statistical analysis;

stop

@enduml
